from enum import Enum, auto


class MessageKey(Enum):
    OPERATIONS_LIST = auto()
    WORK_WITH_DATA = auto()
    WORK_WITH_FILE = auto()
    TOP_N = auto()
    GET_N = auto()
    GET_DATA = auto()
    FILTER_COUNTRY = auto()
    GREETINGS = auto()
    OPERATION_NUMBER = auto()
    NOT_DATA = auto()
    COUNTRY = auto()
    CALLSIGN = auto()
    FILENAME = auto()
    DATA_RECEIVED = auto()
    DATA_RECEIVED_NOT = auto()
    SAVE_ALL = auto()
    SAVE_PLANE = auto()
    GET_PLANE = auto()
    GET_PLANE_ALL = auto()
    DELETE_PLANE = auto()
    DELETE_PLANE_ALL = auto()
    PROGRAM_END = auto()
    FILE_JSON = auto()
    FILE_SQL = auto()
    FILENAME_STD = auto()
    FILENAME_USER = auto()
    MENU_MAIN = auto()
    MENU_DATA = auto()
    MENU_DATA_OPERATIONS = auto()
    MENU_FILE_TYPE = auto()
    MENU_FILE_OPERATIONS = auto()
    MENU_FILE_SAVE = auto()
    MENU_FILE_GET = auto()
    MENU_FILE_DEL = auto()
    MENU_FILENAME = auto()
